//------------------------------------------------------------------------------
// <auto-generated>
//     AppState code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to AppState file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using UnityEngine;
using System.Collections;
//using System;
using System.Collections.Generic;

public class AppState  {
	
	//public AppState _instance = null;
	private static int[] _rutaenemigo;
	private static readonly int _numciudadesenemigo = 5;  
	private static int _horasrestantes;
	private static int _ciudadactual;
	private static int _horaactual;
	private static int _diaactual;
	private static int _siguienteobjetivo;
	private static int _intentoscapturadestino;
	public static int[] lugares;
	private static string[] _nombresdias = {"Lun","Mar","Mie","Jue","Vie","Sab","Dom"};
	//holder for reference
	/*
	 * 0. La Paz
	 * 1. Oruro
	 * 2. Potosi
	 * 3. Tarija
	 * 4. Sucre
	 * 5. Cochabamba
	 * 6. Santa Cruz
	 * 7. Beni
	 * 8. Pando
	 * 
	 * /

	public GameObject goGame;
	*/
	/*
	public AppState() {
		Debug.Log("constructor ");
	}
	*/
	/* singleton */
	/*
	public static AppState Instance() { 
		
		if (_instance==null)
		{
			_instance=new AppState() ;
		}
		return _instance;
	}*/
	
	public static void Comienza()
	{
		AppState._horasrestantes = 120;
		AppState._horaactual = 10;
		AppState._diaactual = 0;
		AppState._siguienteobjetivo = 0;
		AppState._intentoscapturadestino = Random.Range(0,3);
		AppState._rutaenemigo = new int[AppState._numciudadesenemigo];

		for (int i=0; i < AppState._numciudadesenemigo; i++)
		{
			int xx;
			bool b;
			do {
				
				b = false;
				xx = Random.Range(1, 9); 
				for (int j=0; j<i; j++)
					if (AppState._rutaenemigo[j] == xx)
						b = true;
			} while (b);
			AppState._rutaenemigo[i] = xx;
		}
		AppState._ciudadactual = 0;
	}
	
	/*
	 * 0. Terminal
	 * 1. Hotel
	 * 2. Mercado
	 * 3. Iglesia
	 * 4. Policia
	 * */
	
	public static int[] LugaresInformacion()
	{
		AppState.lugares = new int[3];
		for (int i=0; i < 3; i++)
		{
			int xx;
			bool b;
			do {
				b = false;
				xx = Random.Range(1, 5); 
				for (int j=0; j<i; j++)
					if (AppState.lugares[j] == xx)
						b = true;
			} while (b);
			AppState.lugares[i] = xx;
			Debug.Log(AppState.lugares[i]);
		}
		return AppState.lugares;
	}

	public static int[] LugaresActuales()
	{
		//AppState.LugaresInformacion ();
		return AppState.lugares;
	}
	
	public static string ObtenerPista(int x)
	{
		string[,] pistas = {  
			{ // la paz
				"Buscaron algun medicamento para evitar el mal de altura",
				"Preguntó por agencias de turismo al lago Titicaca",
				"Se mostraba muy interesado por pasear en teleférico",
				"Dijo que quería conocer la iglesia de San Francisco y su museo",
				"Tenemos algunas pistas de ellos, al parecer piensan hacer un atraco a la bóveda principal del Banco Central de Bolivia"
			} ,
			
			// Oruro
			{
				"Preguntó por coca o algún medicamento que alivie el mal de altura",
				"Me hizo muchas preguntas acerca del carnaval más grande de Bolivia",
				"Dijo que su comida favorita era Charquekan, daría lo que fuera por uno",
				"Mencionó su intención por visitar a la virgen más grande de Bolivia",
				"La sección de Inteligencia investigó y nos informan que piensa asaltar tesoros del museo de la Virgen del Socavón"
			},
			
			// Potosi.
			{
				"Dijo que quería visitar el lugar minero más importante del siglo XIV",
				"Me preguntó acerca de cómo llegar al salar más grande del mundo",
				"Preguntaron por cómo es el clima en la Villa Imperial",
				"Me comentó que tenía cierto temor y fascinación por los lugares donde acuñaban monedas",
				"No tenemos mucha información, pero sabemos que tratará de cruzar la frontera con Argentina",
				
			},
			// Tarija.-
			{
				"Preguntaron si es adecuado pescar en esta época en el río Guadalquivir",
				"Solicitaron información turística sobre la ruta del vino",
				"Después de almorzar, dijo que en su siguiente destino iba a servirse un riquísimo Saice",
				"Estaba muy interesado en conocer la festividad de Chaguaya y la historia del Moto Mendez",
				"Sólo sabemos que está interesado por conocer el Castillo Azul"
			},
			{//Chuquisaca
				"No creian que en Bolivia existe un parque de dinosaurios.",
				"Comentaban de conocer la plaza 25 de mayo.",
				"Queria probar el mejor mondongo.",
				"Interesados en Visitar las campanas del primer grito libertario.",
				"Preguntaron por unos abogados de la corte suprema de justicia."
			},
			//Cochabamba
			{
				"Preguntaron por el precio del ticket del teleférico.",
				"Preguntaron por la distancia del cristo a la ciudad.",
				"Interesados en visitar el tipnis",
				"Querían visitar la virgen de urkupiña",
				"Querian conocer el chapare"
			},
			//Santa Cruz
			{
				"Comentaron sobre lo divertido de moverse en vehiculo entre los anillos de la ciudad",
				"Preguntaron por el lugar donde fallecio el che Guevara",
				"Comentaron de visitar el jardín botanico",
				"Interesados en visitar las misiones jesuiticas",
				"Preguntaron por la distancia entre la ciudad y la iglesia de la virgen de cotoca"
			},
			//Beni
			{
				"Preguntaron por el caudal del rio mamore en esta época del año",
				"Comentaron estar interesados en relajarse en la laguna Suarez.",
				"Interesados en el parque nacional madidi.",
				"Preguntaron por la clase de animales que hay en la amazonia boliviana",
				"Interesados en conocer a los delfines rosados de la amazonia boliviana."
			},
			//Pando
			{
				"Preguntaron por la proximidad del puente que une a Brasil con Bolivia.",
				"Comentaron en visitar al departamento menos poblado de Bolivia.",
				"Interesados en la pesca en el rio madre de dios.",
				"Preguntaron por el parque piñata.",
				"Interesados en conocer a la ciudad mas cara de Bolivia."
			}
		};
		string[] nose = {"El clima esta muy raro ultimamente",
			"No hemos visto nada extraño por aqui, gracias a Dios",
			"Esta ciudad es muy tranquila, usted viene seguido por aqui?",
			"Ocurren muchas cosas por aqui, por ejemplo hace dias llego el Papa Francisco"};
		AppState.disminuirHoras(1);
		if (AppState._ciudadactual == AppState._rutaenemigo[AppState._siguienteobjetivo]) {
			if (AppState._intentoscapturadestino == 0) 
				return "ENCONTRADO";
			else {
				string[] raro = {"La policia esta haciendo varios operativos de manera muy evidente, algo raro pasa",
					"Solo le puedo decir que tenga mucho cuidado, hay tension en muchos lugares de la ciudad",
					"Una banda muy peligrosa esta presente en la ciudad, tenga precaucion"};
				return raro[Random.Range(0,raro.Length)];
			}
		}
		else if (AppState._ciudadactual == 0 || (AppState._siguienteobjetivo > 0 && AppState._ciudadactual == AppState._rutaenemigo[AppState._siguienteobjetivo - 1]))
			return pistas[AppState._rutaenemigo[ AppState._siguienteobjetivo ], x];
		else return nose[Random.Range(0,nose.Length)];
	}
	
	private static void disminuirHoras(int n)
	{
		AppState._horasrestantes -= n; 
		AppState._horaactual += n;
		if (AppState._horaactual >= 24)
		{
			AppState._horaactual -= 24;
			AppState._diaactual++;
		}
		if (AppState._horaactual >= 23 || AppState._horaactual <= 6)
			AppState.disminuirHoras(8);
		
		// si esta entre 21 y 7, sumar 8 horas de sueño
		
		
	}
	
	public static string HoraActual()
	{
		return AppState._horaactual + ":00";
	}
	
	public static string DiaActual()
	{
		return AppState._nombresdias[AppState._diaactual];
	}
	
	public static void Viajar(int x)
	{
		AppState._ciudadactual = x;
		if (x == AppState._rutaenemigo[AppState._siguienteobjetivo] && AppState._siguienteobjetivo < AppState._numciudadesenemigo)
			AppState._siguienteobjetivo++;
		AppState.disminuirHoras(10);
	}
	
	
	
}

